# Generated by Django 2.1.1 on 2019-01-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('likes', models.BigIntegerField(default=0)),
            ],
        ),
    ]
